-- Inserción de empresas
INSERT INTO empresa (correo, direccion, nombre, telefono) VALUES ('empresa1@example.com', 'Dirección 1', 'Empresa Uno', '1234567890');
INSERT INTO empresa (correo, direccion, nombre, telefono) VALUES ('empresa2@example.com', 'Dirección 2', 'Empresa Dos', '9876543210');

-- Inserción de ofertas asociadas a empresas
INSERT INTO oferta (nombre, descripcion, horario, puesto, jornada, fecha, empresa_id) VALUES ('Ingeniero en Desarrollo Web', 'Desarrollo web utilizando las últimas tecnologías y mejores prácticas para crear experiencias web de alta calidad. Colaboración estrecha con equipos multidisciplinarios para lograr soluciones innovadoras y eficientes.', '9am - 5pm', 'full-stack', 'diurna', '15 mayo', 1);
INSERT INTO oferta (nombre, descripcion, horario, puesto, jornada, fecha, empresa_id) VALUES ('Analista de Datos Senior', 'Análisis avanzado de datos para extraer información valiosa y proporcionar insights clave. Utilización de herramientas analíticas y estadísticas para la toma de decisiones estratégicas.', '8am - 4pm', 'analista', 'diurna', '20 junio', 2);
INSERT INTO oferta (nombre, descripcion, horario, puesto, jornada, fecha, empresa_id) VALUES ('Diseñador Gráfico Creativo', 'Diseño gráfico enfocado en la creación de piezas visuales impactantes y atractivas. Desarrollo de conceptos creativos y colaboración estrecha con el equipo de marketing para transmitir mensajes efectivos.', '10am - 6pm', 'diseñador', 'diurna', '8 julio', 1);
INSERT INTO oferta (nombre, descripcion, horario, puesto, jornada, fecha, empresa_id) VALUES ('Desarrollador Móvil Experimentado','Desarrollo de aplicaciones móviles de alto rendimiento para plataformas iOS y Android. Implementación de funcionalidades innovadoras y resolución de problemas complejos en el desarrollo móvil.', '1pm - 9pm', 'mobile developer', 'tarde', '3 agosto', 2);
INSERT INTO oferta (nombre, descripcion, horario, puesto, jornada, fecha, empresa_id) VALUES ('Especialista en Soporte Técnico',  'Brindar soporte técnico de alta calidad a usuarios y clientes, resolver problemas de hardware y software de manera eficiente. Colaborar con equipos internos para mejorar continuamente la calidad del soporte.', '12pm - 8pm', 'soporte', 'tarde', '18 septiembre', 1);
INSERT INTO oferta (nombre, descripcion, horario, puesto, jornada, fecha, empresa_id) VALUES ('Estratega de Marketing Digital', 'Desarrollo e implementación de estrategias de marketing digital para aumentar la visibilidad de la marca y generar leads. Utilización de herramientas analíticas para medir el rendimiento de las campañas y ajustar estrategias según sea necesario.', '10am - 6pm', 'marketing', 'diurna', '22 octubre', 2);
INSERT INTO oferta (nombre, descripcion, horario, puesto, jornada, fecha, empresa_id) VALUES ('Desarrollador de Juegos Profesional', 'Creación de juegos interactivos y emocionantes, desde la concepción de la idea hasta la implementación. Colaboración con diseñadores y artistas para lograr experiencias de juego cautivadoras.', '2pm - 10pm', 'game developer', 'tarde', '5 noviembre', 2);
INSERT INTO oferta (nombre, descripcion, horario, puesto, jornada, fecha, empresa_id) VALUES ('Administrador de Sistemas Avanzado', 'Administración y mantenimiento de sistemas informáticos, garantizando la disponibilidad y seguridad de la infraestructura. Implementación de soluciones eficientes para mejorar la eficacia operativa.', '9am - 5pm', 'sysadmin', 'diurna', '14 diciembre', 1);
INSERT INTO oferta (nombre, descripcion, horario, puesto, jornada, fecha, empresa_id) VALUES ('Gerente de Recursos Humanos', 'Gestión integral de recursos humanos, desde la contratación hasta el desarrollo profesional. Implementación de políticas y prácticas que promuevan un ambiente laboral saludable y productivo.', '8am - 4pm', 'HR manager', 'diurna', '7 enero', 2);
INSERT INTO oferta (nombre, descripcion, horario, puesto, jornada, fecha, empresa_id) VALUES ('Desarrollador de Aplicaciones Experimentado', 'Desarrollo y mantenimiento de aplicaciones empresariales, enfocado en la creación de soluciones robustas y escalables. Colaboración con equipos multifuncionales para cumplir con los requisitos del cliente.', '11am - 7pm', 'app developer', 'tarde', '23 febrero', 1);



-- Datos de usuarios
INSERT INTO USUARIO ( EMAIL , PASSWORD , USERNAME ) VALUES ('correo1@correo1.com', '1234', 'Gerardo')
INSERT INTO USUARIO_AUTHORITIES VALUES (1, 'READ');